name: Programs Watcher Automation

on:
  schedule:
    - cron: '0 */4 * * *' # Automatically runs every 4 hours, 24/7
  workflow_dispatch: # Allows you to also push a button and run it manually anytime

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Inject hidden secrets into config.yml
      env:
        WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        MONGO: ${{ secrets.MONGO_URI }}
      run: |
        python3 -c "
        import os
        with open('config.yml', 'r') as f:
            lines = f.readlines()
        
        for i, line in enumerate(lines):
            if 'programs_watcher:' in line:
                parts = line.split(':', 1)
                lines[i] = f'{parts[0]}: {os.environ[\"WEBHOOK\"]}\n'
            elif 'uri:' in line:
                parts = line.split(':', 1)
                lines[i] = f'{parts[0]}: {os.environ[\"MONGO\"]}\n'
        
        with open('config.yml', 'w') as f:
            f.writelines(lines)
        "

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute program tracker
      run: |
        python main.py
